"""updating bases

Revision ID: 0f1c4cd6b9f8
Revises: ce3552999901
Create Date: 2023-09-05 03:56:17.716648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1c4cd6b9f8'
down_revision = 'ce3552999901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payments_bill_id_bills'), 'bills', ['bill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_bill_id_bills'), type_='foreignkey')
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
