"""updating bases

Revision ID: 8375a29b5ff0
Revises: 0f1c4cd6b9f8
Create Date: 2023-09-05 04:00:29.163446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8375a29b5ff0'
down_revision = '0f1c4cd6b9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_charges_bill_id_bills'), 'bills', ['bill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_charges_bill_id_bills'), type_='foreignkey')
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
