"""updating bases

Revision ID: ce3552999901
Revises: fbfd07069502
Create Date: 2023-09-05 03:03:57.031445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3552999901'
down_revision = 'fbfd07069502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bills_lease_id_leases'), 'leases', ['lease_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bills_lease_id_leases'), type_='foreignkey')
        batch_op.drop_column('lease_id')

    # ### end Alembic commands ###
