"""added base

Revision ID: ea3cb20fb672
Revises: 298f6aa1304a
Create Date: 2023-09-04 23:51:32.960489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3cb20fb672'
down_revision = '298f6aa1304a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_leases_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_leases_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
